name: "Tests"

on:
    push:
    pull_request:

jobs:
    tests:
        name: Tests
        strategy:
            matrix:
                symfony-version:
                    - "7.4.*"
                    - "8.1.*"
                php-version:
                    - "8.4"
                    - "8.5"
                operating-system:
                    - "ubuntu-latest"

        runs-on: ${{ matrix.operating-system }}
        env:
            COMPOSER_MEMORY_LIMIT: -1
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: pcov
                    tools: composer:v2
                    php-version: "${{ matrix.php-version }}"
                    extensions: "pdo, pdo_mysql, pdo_pgsql"
                    ini-values: memory_limit=-1

            -   name: "Get Composer Cache Directory"
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"
            -   name: "Cache Composer dependencies"
                uses: "actions/cache@v4"
                with:
                    path: |
                        ${{ steps.composer-cache.outputs.dir }}
                    key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.lock') }}"
                    restore-keys: |
                        php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

            -   name: "Require symfony/flex"
                run: "composer global require symfony/flex --no-scripts --no-plugins"

            -   name: "Enable symfony/flex plugin"
                run: "composer global config --no-scripts --no-plugins allow-plugins.symfony/flex true"

            -   name: "Install dependencies"
                run: "SYMFONY_REQUIRE='${{ matrix.symfony-version }}' composer update -n --prefer-dist"

            -   name: "Test"
                run: "composer test-coverage"

            -   name: "Upload coverage results to Coveralls"
                uses: "coverallsapp/github-action@v2"
                with:
                    file: "build/logs/clover.xml"
                    format: "clover"
                    parallel: true
                    flag-name: "php-${{ matrix.php-version }}-symfony-${{ matrix.symfony-version }}"

    coveralls-finish:
        name: Coveralls finish
        needs: tests
        if: ${{ always() }}
        runs-on: ubuntu-latest
        steps:
            -   name: "Close parallel Coveralls build"
                uses: "coverallsapp/github-action@v2"
                with:
                    parallel-finished: true
